name: SLWaypoints
main: io.github.slazurin.slwaypoints.SLWaypoints
version: 1.0.0
author: Azurin
api-version: 1.17

commands:
  wp:
    description: Teleport to a waypoint
    permission-message: You do not have permission to use this command.
    usage: /wp <waypoint_name>
    permission: slwp.wp
  wps:
    description: Show available waypoints
    permission-message: You do not have permission to use this command.
    usage: /wps <page_number>
    permission: slwp.wps
  setwp:
    description: Set a new waypoint
    permission-message: You do not have permission to use this command.
    usage: /setwp <waypoint_name> <description>
    permission: slwp.setwp
  delwp:
    description: Delete a waypoint
    permission-message: You do not have permission to use this command.
    usage: /delwp <waypoint_name>
    permission: slwp.setwp
  debuginfo:
    description: Check api data for SLWaypoint
    permission-message: You do not have permission to use this command.
    usage: /debuginfo
    permission: slwp.debuginfo

permissions:
  slwp.*:
    default: op
    children:
      slops.wp: true
      slops.wps: true
      slops.setwp: true
      slops.delwp: true
      slops.debuginfo: true
  slwp.wp:
    description: Allows player to use the /wp command
    default: true
  slwp.wps:
    description: Allows player to use the /wps command
    default: true
  slwp.setwp:
    description: Allows player to use the /setwp command
    default: op
  slwp.delwp:
    description: Allows player to use the /delwp command
    default: op
  slwp.debuginfo:
    description: Allows player to use the /debuginfo command
    default: op